### PR TITLE
feat: Allow tolerations for ephemeral agents

### PR DESCRIPTION
**Pull request by BenjaminDecreusefond**
Hi @alfespa17 ! 

We would like to use that feature to schedule our jobs on the correct node instance ! Do you think that could benefit to Terrakube users ?

### CODE REVIEW

**Comment by alfespa17** [comment]
I saw some messages regarding support for toleration [here](https://github.com/orgs/AzBuilder/discussions/1576) from @klinux and I saw some message in the slack community about it, so I think it will be a good addition

**Comment by BenjaminDecreusefond** [comment]
Oh great ! coming on point !

**Comment by alfespa17** [comment]
I guess this will allow to create it like this `key1=value1:NoSchedule;key2=value2:NoSchedule` right?

I saw that `toleration.setOperator("Exists");` is hardcoded. Is there a way to make that more flexible?

```
 String[] info = tolerationData.split("=");
                Toleration toleration = new Toleration();
                toleration.setKey(info[0]);
                toleration.setOperator("Exists");
                toleration.setEffect(info.length > 1 ? info[1] : null);
                tolerations.add(toleration);
```

**Comment by BenjaminDecreusefond** [comment]
It would allow something like this :
`"service.your-toleration/terrakube=NoSchedule";"service.yourtoleration2/terrakube=NoSchedule"`

I'll try to variabilize the operator !

**Comment by BenjaminDecreusefond** [comment]
Hmm,

Tolerations could be defined without Effect for instance, If you omit the effect, the toleration applies to any taint with the same key and operator, regardless of the effect. This can be useful when:
- Flexibility is desired: You want a pod to tolerate any taint with a given key/operator, irrespective of the effect.
- Generic configuration: You don’t know all the possible effects the node taints might have, but you still want the pod to tolerate them.
	
What do you think ? @alfespa17

**Comment by BenjaminDecreusefond** [comment]
Also @alfespa17, I was wondering if it was possible to add a protection to workspaces to prevent their destruction using Terraform if they are managing resources(or even from the UI). Because it could lead to plenty of unmanaged resources unfortunately : /

**Comment by alfespa17** [comment]
By the way I will create release 2.24.0 by the end of this week, so if you can test this feature let me know if it require some other adjustment

**Comment by BenjaminDecreusefond** [comment]
Hmm the issue with that is that it does not cover the changes. You can destroy a workspace by running a Terraform apply. If you add a workspace configuration from a branch. And then apply that same configuration from another branch that did not merge the first branch you will be able to destroy the workspace.

**Comment by alfespa17** [comment]
If you "lock" the workspace you wont be able to do any changes

**Comment by BenjaminDecreusefond** [comment]
I did not tested the lock feature, what does it do?

**Comment by alfespa17** [comment]
You "lock" the workspace inside the settings here

image

Once is locked you will see this message

image

If you execute any job it will be pending forever until you unlock the workspace or terrakube cancel those jobs after 6 hours

image

You will also see this inside the logs:

image

If you are using the CLI driven workflow remote execution will show

**Comment by BenjaminDecreusefond** [comment]
Thank you !

**Comment by klinux** [comment]
Hello @alfespa17 and @BenjaminDecreusefond,

There's no support to value in toleration, example:

```
        tolerations:
          - key: "pool"
            value: "spot"
            operator: "Equal"
            effect: "NoSchedule"
```
Or I misunderstanding?

**Comment by alfespa17** [comment]
> key:operator:effect
Hello @klinux 

For now it support `key:operator:effect`, If you have any idea to improved it all PR are welcome

**Comment by klinux** [comment]
@alfespa17 what do you think about this PR to support value in tolerations?

https://github.com/AzBuilder/terrakube/pull/1592

**Comment by alfespa17** [comment]
> @alfespa17 what do you think about this PR to support value in tolerations?
> 
> #1592

I have merged that PR

**Comment by klinux** [comment]
@alfespa17 what is the planning to release this options? Only in 2.25.0?

Thank you

**Comment by alfespa17** [comment]
> @alfespa17 what is the planning to release this options? Only in 2.25.0?
> 
> Thank you

I could add it in 2.24.1 if you need it? It is a small change

**Comment by alfespa17** [comment]
Done @klinux 

I create the new release with your fixes, the image will be ready in some minutes

https://github.com/AzBuilder/terrakube/releases/tag/2.24.1

**Pull request merged**
