### PR TITLE
fix: Move ORGANIZATION_ARCHIVE retrieval from localStorage to sessionStorage to prevent workspace conflicts across tabs

### PR DESCRIPTION
**Pull request by ilkerispir**

### CODE REVIEW

**Comment by ilkerispir** [comment]
Hello @alfespa17, @jcanizalez,

I've created a PR related to issue https://github.com/AzBuilder/terrakube/issues/1266

**Comment by alfespa17** [comment]
I think this will also fix https://github.com/AzBuilder/terrakube/issues/1170

**Comment by alfespa17** [comment]
thank you @ilkerispir

**Comment by ilkerispir** [comment]
Yes, correct @alfespa17. I haven't seen that issue but we are having the same problem.

**Comment by ilkerispir** [comment]
@alfespa17, thank you for merging the PR, and could you please deploy a new beta release? I will test it in my environment.

**Pull request merged**
