### PR TITLE
feat: enhance branch matching with regex

### PR DESCRIPTION
**Pull request by BenjaminDecreusefond**
Hi @alfespa17 !

Following our discussion on this [topic](https://github.com/AzBuilder/terraform-provider-terrakube/issues/83) I'd like to propose a new way to do the matching for the branch list. The idea is as follow
- Be able to say I want to match all branch except these ones
- Keep the previous logic with startsWith branch

The only thing is that I do not automatically return `True` when the branch is the same as the workspace's default branch. I don't know if this is an issue ? 

It's just a proposal for us to be able to achieve our goals ! Lemme know if you approve it :) 

Regards

### CODE REVIEW

**Comment by BenjaminDecreusefond** [comment]
hey @alfespa17 would you know why in the previous behavior we were returning true if the branch matched the workspace default branch ?

**Comment by alfespa17** [comment]
> hey @alfespa17 would you know why in the previous behavior we were returning true if the branch matched the workspace default branch ?

I the beginning we only supported push events in one single branch the default one, but that behavior changed some time ago

**Comment by BenjaminDecreusefond** [comment]
Okay ! So do you think we can merge that PR ?

**Comment by alfespa17** [comment]
> Okay ! So do you think we can merge that PR ?

I will check the logic later

**Comment by stanleyz** [comment]
> The only thing is that I do not automatically return True when the branch is the same as the workspace's default branch. I don't know if this is an issue ?

It's not strictly required, but I believe that's the same thinking behind the below codes.

1. Return true if it matches the workspace default folder
https://github.com/AzBuilder/terrakube/blob/e30c9863d034fb8b7908ce566dab2a08a276215d/api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java#L224

2. Use the workspace default template if the branch is the workspace default branch.
https://github.com/AzBuilder/terrakube/blob/e30c9863d034fb8b7908ce566dab2a08a276215d/api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java#L98

If you are going to change the behaviour here, it's probably good to make it consistent for the above item 1?

This PR greatly enhances the flexibility to match different branches, but since you've already gone down the path of some regex matching, should we use a similar behaviour as the file matching? 

https://github.com/AzBuilder/terrakube/blob/e30c9863d034fb8b7908ce566dab2a08a276215d/api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java#L229

**Comment by BenjaminDecreusefond** [comment]
hey @stanleyz !

I think you're right ! It seems like the code is already matching with regex folder paths ! Maybe we should just remove the behavior of returning true if it matches workspace's default files ? To me it seems like enough

**Comment by BenjaminDecreusefond** [comment]
hey @stanleyz @alfespa17 !

I just changed the behavior to use regex for branches as well so everyone is using the same logic. I also remove the workspace default path matching for the file finding so we have much more freedoms when designing webhooks !

Would you know if it is possible to attach several [webhooks](https://registry.terraform.io/providers/AzBuilder/terrakube/latest/docs/resources/workspace_webhook) to a single workspace ?

thanks !

**Comment by alfespa17** [comment]
I added some comments @BenjaminDecreusefond

**Comment by BenjaminDecreusefond** [comment]
Hi @alfespa17 ! 

I'm not seeing your comments unfortunately ! :/ 
However, I think keeping the behavior of matching the workspace default branch will create duplicate trigger:
- One trigger from the base webhook of the default workspace branch
- Second trigger from the webhook created for `feat` or `fix` branches
 What do you think ?

**Comment by alfespa17** [comment]
These are the comments

image

image

**Comment by alfespa17** [comment]
> Hi @alfespa17 !
> 
> I'm not seeing your comments unfortunately ! :/ However, I think keeping the behavior of matching the workspace default branch will create duplicate trigger:
> 
> * One trigger from the base webhook of the default workspace branch
> * Second trigger from the webhook created for `feat` or `fix` branches
> 
> What do you think ?

You can do this with the existing code, the default branch will trigger the default template and in the webhook branches you can put "feat,fix" and that should work.

**Comment by alfespa17** [comment]
> thanks @alfespa17 !
> 
> Hmmm I think since there is already a webhook created by the workspace by default which matches its default branch master and then another webhook which matches for instance `feat` branch, removing this behavior will not break the current logic ?

If you remove this part changes in any directory will trigger a job inside Terrakube, for example if we have 10 folders managed inside Terrakube we only want to trigger the workspace execution for changes inside 1 particular folder.

```java
            if (file.startsWith(workspaceFolder)) {
                log.info("Changed file {} in set workspace path {}", file, workspaceFolder);
                return true;
            }
```

But if you have like several terraform modules and your workspace depends on that particular module you can also have changes trigger a job for some expression like this "modules/my-dependency-module/*"

this is why you see this in the current code:

```
for (String file : files) {
            if (file.startsWith(workspaceFolder)) {
                log.info("Changed file {} in set workspace path {}", file, workspaceFolder);
                return true;
            }
            for (int i = 0; i < triggeredPath.length; i++) {
                if (file.matches(triggeredPath[i])) {
                    log.info("Changed file {} matches set trigger pattern {}", file, triggeredPath[i]);
                    return true;
                }
            }
        }
```

The issue behind that logic was this one 

https://github.com/AzBuilder/terrakube/issues/654#issuecomment-1938215535

**Comment by BenjaminDecreusefond** [comment]
What I don't understand from what you're saying is that how can it trigger a job in terrakube whatever the directory we remove since we use a regex matching just after in the code ? Maybe i'm silly and I'm missing smth ? 🤔

**Comment by BenjaminDecreusefond** [comment]
@alfespa17 I updated the PR !

**Pull request merged**
