### PR TITLE
fix: for annotations has been deprecated

### PR DESCRIPTION
**Pull request by dawidmalina**
fix: https://github.com/AzBuilder/terrakube/issues/1419

### CODE REVIEW

**Comment by dawidmalina** [comment]
@alfespa17 i don't understand why it's failing on sonar configuration:
```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar (default-cli) on project terrakube-platform: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to -> [Help 1]
```

**Comment by alfespa17** [comment]
> @alfespa17 i don't understand why it's failing on sonar configuration:
> 
> ```
> Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar (default-cli) on project terrakube-platform: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to -> [Help 1]
> ```

This is because pull request from forks don't have access to the github action secrets, I guess I need to change some setting to allow that

**Comment by dawidmalina** [comment]
I think that this might be fixed with switching to `pull_request_target` [1]. So we might need to change from:
```
name: Build Terrakube Backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
```
to
```
name: Build Terrakube Backend

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
```

[1] https://github.blog/news-insights/product-news/github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

**Comment by alfespa17** [comment]
> I think that this might be fixed with switching to `pull_request_target` [1]. So we might need to change from:
> 
> ```
> name: Build Terrakube Backend
> 
> on:
>   push:
>     branches:
>       - main
>   pull_request:
>     types: [opened, synchronize, reopened]
> ```
> 
> to
> 
> ```
> name: Build Terrakube Backend
> 
> on:
>   push:
>     branches:
>       - main
>   pull_request_target:
>     types: [opened, synchronize, reopened]
> ```
> 
> [1] https://github.blog/news-insights/product-news/github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

Let me check this I will do the change in the pipeline

**Comment by alfespa17** [comment]
I did the change in the pipeline @dawidmalina, I try running the PR again but it failed again with the sonar issue, maybe you need to sync your branch with the new changes

**Comment by dawidmalina** [comment]
Looks much better but still all 4 jobs started.

**Comment by alfespa17** [comment]
> Looks much better but still all 4 jobs started. Probably we need to enable only `pull_request_target` not both.

Yeap, now the `pull_request_target` was successful maybe I will need to add some condition, so it does not execute the `pull_request`, I will check that later today

image

**Comment by dawidmalina** [comment]
I think this might be helpful: https://github.com/orgs/community/discussions/25217#discussioncomment-3246901

**Comment by alfespa17** [comment]
Can you sync your branch again @dawidmalina ? I did some changes maybe it works now

**Comment by dawidmalina** [comment]
All green now :)

**Comment by alfespa17** [comment]
Now it is working, thank you for the suggestions

**Pull request merged**
