### PR TITLE
Adding team API tokens support

### LINKED ISSUE #517: Add support to handle team tokens in the UI
### Feature description 💡

This [PR](https://github.com/AzBuilder/terrakube/pull/505) added support to generate tokens for an specific team.

We need to add support to generate team tokens in the UI using the following endpoints.

Create team tokens:
```
POST {{terrakubeApi}}/access-token/v1/teams
Authorization: Bearer (PERSONAL ACCESS TOKEN)
Request Body:
{
  "days": "1",
  "group": "TERRAKUBE_ADMIN",
  "description": "Sample PAT"
}
```
Get Teams tokens:
```
GET {{terrakubeApi}}/access-token/v1/teams
Authorization: Bearer (PERSONAL ACCESS TOKEN)
Response Body:
[
  {
    "createdDate": "2023-09-18T23:10:02.482+00:00",
    "createdBy": "admin@example.com",
    "updatedDate": "2023-09-18T23:10:02.482+00:00",
    "updatedBy": "admin@example.com",
    "id": "a00d2ee2-81d3-4e2b-ae5f-6a2edd43a0bb",
    "days": 1,
    "group": "TERRAKUBE_ADMIN",
    "description": "Sample PAT"
  }
]
```

Get current user groups:
```
GET {{terrakubeApi}}/access-token/v1/teams/current-teams
Authorization: Bearer (PERSONAL ACCESS TOKEN)
Response Body:
{
  "groups": [
    "TERRAKUBE_ADMIN",
    "TERRAKUBE_DEVELOPERS"
  ]
}
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jcanizalez**
fixes #517 

[Documentation](https://docs.terrakube.io/user-guide/organizations/api-tokens#user-api-tokens-1)

image

image

### CODE REVIEW

**Comment by alfespa17** [comment]
Hey @jcanizalez we added hours and minutes parameters

**Comment by alfespa17** [comment]
In this pr

https://github.com/AzBuilder/terrakube/pull/536

**Comment by jcanizalez** [comment]
ok I will try to add minutes and hours later to the UI

**Comment by jcanizalez** [comment]
when you get some time update the API documentation here https://docs.terrakube.io/api/methods/

**Pull request merged**
