### PR TITLE
handle new event type

### PR DESCRIPTION
**Pull request by BenjaminDecreusefond**

### CODE REVIEW

**Comment by stanleyz** [comment]
hmm, you will need to register the PR events in the `createWebhook` function

https://github.com/AzBuilder/terrakube/blob/1eb779e5b0fb6aae3b5a148f5bea7aec9d7900eb/api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java#L206

Additionally, the `sendCommitStatus` need to be updated so that the status still works for PR based events.

https://github.com/AzBuilder/terrakube/blob/1eb779e5b0fb6aae3b5a148f5bea7aec9d7900eb/api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java#L154

Lastly, need additional toggle for PR based events, I am thinking for the first version we can let both PUSH and PR events share the same set of configurations, meaning webhook branch, path and template settings, in the further version we could add enhance the feature so that each event type can have its dedicated settings, if needed.

https://github.com/AzBuilder/terrakube/blob/1eb779e5b0fb6aae3b5a148f5bea7aec9d7900eb/ui/src/domain/Workspaces/Details.jsx#L1466

**Comment by BenjaminDecreusefond** [comment]
Thanks @stanleyz !

Not sure how to register PR events in the webhook without setting it to work for both Push and pull-request ? Should we use a dynamic parameter ?

**Comment by BenjaminDecreusefond** [comment]
hey @stanleyz !

I did what I could for the `sendCommitStatus` function however, for the JSX and the `createWebhook` function I really need your help as I'm not confortable enough with code base 😅

**Comment by BenjaminDecreusefond** [comment]
hey @stanleyz !

Did you have time to review ? :)

**Comment by stanleyz** [comment]
I can take a look later on, but without the rest of the features or test code, it's going to be hard to test.

I am wondering if you are OK for me to cherry pick your commit and finish the rest features with a new PR, it's going to be a relatively big PR I believe.

**Comment by BenjaminDecreusefond** [comment]
Yep of course you can cherry pick ! 

But I'm wondering you're talking about the JSX part and handling bitbucket and gitlab webhooks ? 
I didn't implement them because i think it was too much for a single PR :/

**Comment by BenjaminDecreusefond** [comment]
Soz btw ! I'm unable to work on the react components I know too little about that !

**Comment by alfespa17** [comment]
> I can take a look later on, but without the rest of the features or test code, it's going to be hard to test.
> 
> I am wondering if you are OK for me to cherry pick your commit and finish the rest features with a new PR, it's going to be a relatively big PR I believe.

I think this will be the best option instead of managing two different PR to add a feature like this one

**Pull request closed without merging**
