### PR TITLE
added mysql port configuration #481

### PR DESCRIPTION
**Pull request by stefano-maglione**
Added possibility to set up the port.  The feature is not tested, can you explain me how to test / reproduce it in the app?

### CODE REVIEW

**Comment by alfespa17** [comment]
Hello @stefano-maglione, you could run a mysql container inside GITPOD using the bitnami image

https://github.com/bitnami/containers/tree/main/bitnami/mysql

I think there is an option to setup the port,username and password according to this documentation

https://github.com/bitnami/containers/tree/main/bitnami/mysql#setting-up-a-replication-cluster

And you could run "./scripts/setupDevelopmentEnvironment.sh" to generate .envApi and add the environment variables.

```
ApiDataSourceType=MYSQL
DatasourceHostname=locahost
DatasourceDatabase=XXXXX
DatasourceUser=xxxx
DatasourcePassword=xxxx
DatasourcePort=xxxx
```

Once the environment variables is complete you should be able to run the API and see the logs

**Comment by alfespa17** [comment]
By the way make sure to update the application-demo.properties adding the new environment variable there too.

Depending of the spring boot profile it could use that file too when loading sample data

**Comment by stefano-maglione** [comment]
> Hello @stefano-maglione, you could run a mysql container inside GITPOD using the bitnami image
> 
> https://github.com/bitnami/containers/tree/main/bitnami/mysql
> 
> I think there is an option to setup the port,username and password according to this documentation
> 
> https://github.com/bitnami/containers/tree/main/bitnami/mysql#setting-up-a-replication-cluster
> 
> And you could run "./scripts/setupDevelopmentEnvironment.sh" to generate .envApi and add the environment variables.
> 
> ```
> ApiDataSourceType=MYSQL
> DatasourceHostname=locahost
> DatasourceDatabase=XXXXX
> DatasourceUser=xxxx
> DatasourcePassword=xxxx
> DatasourcePort=xxxx
> ```
> 
> Once the environment variables is complete you should be able to run the API and see the logs

Thanks, I will try. Can you give me an example on how to run the API?

**Comment by alfespa17** [comment]
> > Hello @stefano-maglione, you could run a mysql container inside GITPOD using the bitnami image
> > https://github.com/bitnami/containers/tree/main/bitnami/mysql
> > I think there is an option to setup the port,username and password according to this documentation
> > https://github.com/bitnami/containers/tree/main/bitnami/mysql#setting-up-a-replication-cluster
> > And you could run "./scripts/setupDevelopmentEnvironment.sh" to generate .envApi and add the environment variables.
> > ```
> > ApiDataSourceType=MYSQL
> > DatasourceHostname=locahost
> > DatasourceDatabase=XXXXX
> > DatasourceUser=xxxx
> > DatasourcePassword=xxxx
> > DatasourcePort=xxxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Once the environment variables is complete you should be able to run the API and see the logs
> 
> Thanks, I will try. Can you give me an example on how to run the API?

You can run the API the following way.

Run script:
```bash
./scripts/setupDevelopmentEnvironment.sh
```

Update the .envAPI with the MYSQL database values and load the values as env variables
```bash
source .envApi
```

Run the API.
```bash
cd api/
mvn spring-boot:run
```

If you are using GITPOD just click the following button.
image

**Comment by stefano-maglione** [comment]
Hello @alfespa17 , in the last commit I fixed some parts. Tested with a mysql container and works perfectly.

**Comment by alfespa17** [comment]
Thank you for your help @stefano-maglione. I merged the change

**Pull request merged**
